// Mock data for the NxtGen Revenue OS platform
// In production, all data is fetched from the database via API routes

export const mockOrganization = {
  id: "org-1",
  name: "Acme Corporation",
  slug: "acme",
  plan: "enterprise",
  industry: "Technology",
  size: "51-200",
};

export const mockUser = {
  id: "user-1",
  name: "Alex Rivera",
  email: "alex@acme.com",
  role: "admin",
  avatar: null,
  jobTitle: "Head of Revenue",
};

export const mockRevenueData = [
  { month: "Jan", mrr: 124000, arr: 1488000, new: 18400, churned: 3200, net: 15200 },
  { month: "Feb", mrr: 138000, arr: 1656000, new: 22100, churned: 8100, net: 14000 },
  { month: "Mar", mrr: 151000, arr: 1812000, new: 19800, churned: 6800, net: 13000 },
  { month: "Apr", mrr: 163000, arr: 1956000, new: 24300, churned: 12300, net: 12000 },
  { month: "May", mrr: 178000, arr: 2136000, new: 28900, churned: 13900, net: 15000 },
  { month: "Jun", mrr: 196000, arr: 2352000, new: 31200, churned: 13200, net: 18000 },
  { month: "Jul", mrr: 214000, arr: 2568000, new: 33800, churned: 15800, net: 18000 },
  { month: "Aug", mrr: 228000, arr: 2736000, new: 29400, churned: 15400, net: 14000 },
  { month: "Sep", mrr: 243000, arr: 2916000, new: 35600, churned: 20600, net: 15000 },
  { month: "Oct", mrr: 261000, arr: 3132000, new: 38200, churned: 20200, net: 18000 },
  { month: "Nov", mrr: 279000, arr: 3348000, new: 41900, churned: 23900, net: 18000 },
  { month: "Dec", mrr: 298000, arr: 3576000, new: 44100, churned: 25100, net: 19000 },
];

export const mockPipelineData = [
  { stage: "Prospecting", count: 47, value: 892000, color: "#6366f1" },
  { stage: "Qualification", count: 38, value: 1240000, color: "#8b5cf6" },
  { stage: "Proposal", count: 24, value: 2180000, color: "#06b6d4" },
  { stage: "Negotiation", count: 15, value: 1890000, color: "#10b981" },
  { stage: "Closed Won", count: 28, value: 3420000, color: "#f59e0b" },
];

export const mockContacts = [
  {
    id: "c1",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah@techcorp.com",
    phone: "+1 (555) 234-5678",
    status: "customer",
    company: "TechCorp Inc",
    jobTitle: "VP of Sales",
    score: 92,
    tags: ["vip", "enterprise"],
    lastContactedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
    source: "Website",
    revenue: 48000,
  },
  {
    id: "c2",
    firstName: "Marcus",
    lastName: "Williams",
    email: "marcus@innovate.io",
    phone: "+1 (555) 345-6789",
    status: "prospect",
    company: "Innovate IO",
    jobTitle: "CEO",
    score: 78,
    tags: ["hot-lead", "saas"],
    lastContactedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    source: "LinkedIn",
    revenue: 0,
  },
  {
    id: "c3",
    firstName: "Elena",
    lastName: "Petrov",
    email: "elena@globalops.com",
    phone: "+1 (555) 456-7890",
    status: "lead",
    company: "Global Ops",
    jobTitle: "CTO",
    score: 65,
    tags: ["inbound"],
    lastContactedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    source: "Webinar",
    revenue: 0,
  },
  {
    id: "c4",
    firstName: "James",
    lastName: "Chen",
    email: "james@buildfast.co",
    phone: "+1 (555) 567-8901",
    status: "customer",
    company: "BuildFast Co",
    jobTitle: "Founder",
    score: 88,
    tags: ["startup", "growth"],
    lastContactedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000),
    source: "Referral",
    revenue: 24000,
  },
  {
    id: "c5",
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya@scalex.ai",
    phone: "+1 (555) 678-9012",
    status: "vip",
    company: "ScaleX AI",
    jobTitle: "Head of Growth",
    score: 97,
    tags: ["vip", "ai", "enterprise"],
    lastContactedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000),
    source: "Partner",
    revenue: 120000,
  },
  {
    id: "c6",
    firstName: "David",
    lastName: "Thompson",
    email: "david@nextstep.co",
    phone: "+1 (555) 789-0123",
    status: "prospect",
    company: "NextStep Co",
    jobTitle: "Director of Marketing",
    score: 71,
    tags: ["marketing"],
    lastContactedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    source: "Paid Ads",
    revenue: 0,
  },
];

export const mockDeals = [
  {
    id: "d1",
    name: "Enterprise License - TechCorp",
    value: 84000,
    stage: "negotiation",
    probability: 80,
    contact: "Sarah Johnson",
    company: "TechCorp Inc",
    owner: "Alex Rivera",
    expectedCloseDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    tags: ["enterprise", "annual"],
  },
  {
    id: "d2",
    name: "ScaleX Platform Expansion",
    value: 240000,
    stage: "proposal",
    probability: 65,
    contact: "Priya Sharma",
    company: "ScaleX AI",
    owner: "Jordan Lee",
    expectedCloseDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    tags: ["expansion", "ai"],
  },
  {
    id: "d3",
    name: "Innovate IO Starter Package",
    value: 18000,
    stage: "qualification",
    probability: 40,
    contact: "Marcus Williams",
    company: "Innovate IO",
    owner: "Sam Park",
    expectedCloseDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    tags: ["starter"],
  },
  {
    id: "d4",
    name: "BuildFast Annual Renewal",
    value: 28800,
    stage: "closed_won",
    probability: 100,
    contact: "James Chen",
    company: "BuildFast Co",
    owner: "Alex Rivera",
    expectedCloseDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    tags: ["renewal"],
  },
  {
    id: "d5",
    name: "NextStep Marketing Suite",
    value: 36000,
    stage: "prospecting",
    probability: 20,
    contact: "David Thompson",
    company: "NextStep Co",
    owner: "Jordan Lee",
    expectedCloseDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    tags: ["marketing"],
  },
];

export const mockCampaigns = [
  {
    id: "camp1",
    name: "Q4 Product Launch Sequence",
    type: "email",
    status: "sending",
    subject: "Introducing the future of revenue intelligence",
    sentAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    stats: { sent: 12400, delivered: 12180, opened: 4872, clicked: 1463, revenue: 84200 },
    audienceSize: 12400,
  },
  {
    id: "camp2",
    name: "Customer Winback - 90 Day Churned",
    type: "email",
    status: "scheduled",
    subject: "We miss you — here's what's new",
    scheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    stats: { sent: 0, delivered: 0, opened: 0, clicked: 0, revenue: 0 },
    audienceSize: 847,
  },
  {
    id: "camp3",
    name: "Weekly Revenue Newsletter",
    type: "email",
    status: "sent",
    subject: "Your weekly growth report is ready",
    sentAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    stats: { sent: 8920, delivered: 8741, opened: 3321, clicked: 892, revenue: 21400 },
    audienceSize: 8920,
  },
  {
    id: "camp4",
    name: "Black Friday SMS Blast",
    type: "sms",
    status: "draft",
    subject: "50% off — today only",
    stats: { sent: 0, delivered: 0, opened: 0, clicked: 0, revenue: 0 },
    audienceSize: 5200,
  },
];

export const mockWorkflows = [
  {
    id: "wf1",
    name: "New Lead Nurture Sequence",
    status: "active",
    trigger: "Contact created",
    enrolledCount: 1240,
    completedCount: 892,
    conversionRate: 28.4,
    steps: 7,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
  },
  {
    id: "wf2",
    name: "Trial to Paid Conversion",
    status: "active",
    trigger: "Trial started",
    enrolledCount: 340,
    completedCount: 98,
    conversionRate: 42.1,
    steps: 12,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
  },
  {
    id: "wf3",
    name: "Onboarding Milestone Tracker",
    status: "active",
    trigger: "Deal closed won",
    enrolledCount: 78,
    completedCount: 56,
    conversionRate: 91.8,
    steps: 9,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: "wf4",
    name: "Churn Prevention — At Risk Accounts",
    status: "paused",
    trigger: "Health score drops below 40",
    enrolledCount: 23,
    completedCount: 8,
    conversionRate: 34.8,
    steps: 5,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
  },
  {
    id: "wf5",
    name: "NPS Detractor Recovery",
    status: "active",
    trigger: "NPS score 0-6 submitted",
    enrolledCount: 45,
    completedCount: 31,
    conversionRate: 68.9,
    steps: 4,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
  },
];

export const mockTickets = [
  {
    id: "t1",
    ticketNumber: "TKT-1042",
    subject: "API integration returning 401 errors",
    status: "in_progress",
    priority: "high",
    contact: "Sarah Johnson",
    company: "TechCorp Inc",
    assignee: "Mike Chen",
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    firstResponseAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    satisfactionScore: null,
  },
  {
    id: "t2",
    ticketNumber: "TKT-1041",
    subject: "Billing discrepancy on invoice #INV-2847",
    status: "open",
    priority: "medium",
    contact: "James Chen",
    company: "BuildFast Co",
    assignee: null,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    firstResponseAt: null,
    satisfactionScore: null,
  },
  {
    id: "t3",
    ticketNumber: "TKT-1040",
    subject: "Feature request: bulk import for contacts",
    status: "waiting",
    priority: "low",
    contact: "Priya Sharma",
    company: "ScaleX AI",
    assignee: "Alex Rivera",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    firstResponseAt: new Date(Date.now() - 1.8 * 24 * 60 * 60 * 1000),
    satisfactionScore: null,
  },
  {
    id: "t4",
    ticketNumber: "TKT-1039",
    subject: "Dashboard not loading — spinning indefinitely",
    status: "resolved",
    priority: "critical",
    contact: "Elena Petrov",
    company: "Global Ops",
    assignee: "Mike Chen",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    firstResponseAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000),
    satisfactionScore: 5,
  },
];

export const mockActivities = [
  {
    id: "a1",
    type: "email",
    subject: "Follow-up on enterprise proposal",
    contact: "Sarah Johnson",
    company: "TechCorp Inc",
    user: "Alex Rivera",
    completedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    outcome: "Positive response, scheduling demo",
  },
  {
    id: "a2",
    type: "call",
    subject: "Discovery call - 45 min",
    contact: "Marcus Williams",
    company: "Innovate IO",
    user: "Jordan Lee",
    completedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    outcome: "Qualified - moving to proposal stage",
    duration: 45,
  },
  {
    id: "a3",
    type: "meeting",
    subject: "Quarterly business review",
    contact: "Priya Sharma",
    company: "ScaleX AI",
    user: "Alex Rivera",
    scheduledAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
    duration: 60,
  },
  {
    id: "a4",
    type: "note",
    subject: "Key decision maker identified",
    contact: "David Thompson",
    company: "NextStep Co",
    user: "Sam Park",
    completedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: "a5",
    type: "email",
    subject: "Onboarding welcome sequence - Day 3",
    contact: "James Chen",
    company: "BuildFast Co",
    user: "System",
    completedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    outcome: "Opened and clicked CTA",
  },
];

export const mockProducts = [
  {
    id: "p1",
    name: "Revenue OS Starter",
    type: "subscription",
    price: 97,
    interval: "month",
    description: "Perfect for small teams getting started",
    features: ["Up to 5 users", "5,000 contacts", "Email campaigns", "Basic automation"],
    isActive: true,
    totalRevenue: 124800,
    activeSubscriptions: 1287,
  },
  {
    id: "p2",
    name: "Revenue OS Professional",
    type: "subscription",
    price: 297,
    interval: "month",
    description: "For growing businesses that need more power",
    features: ["Up to 25 users", "50,000 contacts", "Advanced automation", "AI features", "Analytics"],
    isActive: true,
    totalRevenue: 389600,
    activeSubscriptions: 1313,
  },
  {
    id: "p3",
    name: "Revenue OS Enterprise",
    type: "subscription",
    price: 997,
    interval: "month",
    description: "Unlimited power for scaling enterprises",
    features: ["Unlimited users", "Unlimited contacts", "Custom integrations", "Priority support", "SLA"],
    isActive: true,
    totalRevenue: 892400,
    activeSubscriptions: 895,
  },
];

export const mockKPIs = {
  mrr: { value: 298400, change: 6.9, trend: "up" },
  arr: { value: 3580800, change: 6.9, trend: "up" },
  totalContacts: { value: 48291, change: 12.4, trend: "up" },
  activeDeals: { value: 124, change: -3.2, trend: "down" },
  pipelineValue: { value: 8240000, change: 18.7, trend: "up" },
  avgDealSize: { value: 66451, change: 22.9, trend: "up" },
  winRate: { value: 38.4, change: 4.2, trend: "up" },
  churnRate: { value: 2.1, change: -0.4, trend: "up" },
  cac: { value: 1840, change: -8.3, trend: "up" },
  ltv: { value: 28400, change: 14.2, trend: "up" },
  nps: { value: 67, change: 5, trend: "up" },
  openTickets: { value: 43, change: -12.1, trend: "up" },
};

export const mockChannelData = [
  { name: "Organic Search", value: 34, color: "#6366f1" },
  { name: "Paid Ads", value: 28, color: "#8b5cf6" },
  { name: "Referral", value: 18, color: "#06b6d4" },
  { name: "Social", value: 11, color: "#10b981" },
  { name: "Email", value: 9, color: "#f59e0b" },
];

export const mockConversionFunnel = [
  { stage: "Visitors", count: 48420 },
  { stage: "Leads", count: 9284 },
  { stage: "MQLs", count: 3142 },
  { stage: "SQLs", count: 892 },
  { stage: "Opportunities", count: 346 },
  { stage: "Customers", count: 124 },
];

export const mockAIInsights = [
  {
    id: "ai1",
    type: "opportunity",
    priority: "high",
    title: "High-value deal at risk of going cold",
    body: "Enterprise License - TechCorp has had no activity in 8 days. Based on historical patterns, deals in negotiation stage without activity for 7+ days have a 43% higher close rate after a personalized follow-up.",
    action: "Send AI-crafted follow-up",
    impact: "+$84K potential",
    contact: "Sarah Johnson",
  },
  {
    id: "ai2",
    type: "churn",
    priority: "high",
    title: "Churn risk detected — ScaleX AI",
    body: "Health score dropped from 82 to 41 over the last 14 days. Login frequency is down 68%, and they have 3 unresolved support tickets. Recommend proactive outreach with a success playbook.",
    action: "Launch churn prevention workflow",
    impact: "Save $120K ARR",
    contact: "Priya Sharma",
  },
  {
    id: "ai3",
    type: "expansion",
    priority: "medium",
    title: "Expansion opportunity — BuildFast Co",
    body: "BuildFast Co is approaching their contact limit (94% usage) and has been actively using automation features. They're a strong candidate for an upgrade to Professional plan.",
    action: "Create expansion proposal",
    impact: "+$10.8K ARR",
    contact: "James Chen",
  },
  {
    id: "ai4",
    type: "campaign",
    priority: "medium",
    title: "Email campaign optimization available",
    body: "Your Q4 Product Launch campaign has a 39.3% open rate — 12% above industry average. However, click-to-open rate is only 30%. Personalizing CTAs using contact role data could improve clicks by an estimated 28%.",
    action: "Apply AI personalization",
    impact: "+$23K projected revenue",
  },
];

export const mockTeamPerformance = [
  {
    id: "u1",
    name: "Alex Rivera",
    role: "Head of Revenue",
    avatar: null,
    deals: 34,
    won: 13,
    revenue: 892400,
    winRate: 38.2,
    quota: 900000,
    quotaAttainment: 99.2,
  },
  {
    id: "u2",
    name: "Jordan Lee",
    role: "Account Executive",
    avatar: null,
    deals: 28,
    won: 9,
    revenue: 634200,
    winRate: 32.1,
    quota: 700000,
    quotaAttainment: 90.6,
  },
  {
    id: "u3",
    name: "Sam Park",
    role: "Account Executive",
    avatar: null,
    deals: 22,
    won: 10,
    revenue: 712800,
    winRate: 45.5,
    quota: 700000,
    quotaAttainment: 101.8,
  },
  {
    id: "u4",
    name: "Maya Thompson",
    role: "SDR",
    avatar: null,
    deals: 18,
    won: 6,
    revenue: 312400,
    winRate: 33.3,
    quota: 300000,
    quotaAttainment: 104.1,
  },
];
